.TH "algo" 3 "Fri Oct 16 2020" "FlexTyper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algo
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020, Wasserman lab 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FlexTyper from the source code\&.
