.TH "ft" 3 "Fri Oct 16 2020" "FlexTyper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQueryClass\fP"
.br
.RI "A class that contains information for one query ID, Type pair\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2020, Wasserman lab 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for FlexTyper from the source code\&.
