version: 2
jobs:
  build:
    docker:
        - image: "ubuntu:latest"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y curl graphviz cmake libdivsufsort-dev libdivsufsort3 libsdsl-dev libsdsl3 libgtest-dev libboost-all-dev g++-8 gcc-8 dialog && apt-get install -y whiptail git libseqan2-dev zlib1g-dev libbz2-dev cmake wget libx11-dev libdbus-glib-1-2 qt5-qmake libx11-xcb-dev libglu1-mesa-dev libxrender-dev build-essential qt5-default qtdeclarative5-dev libqt5webview5-dev'
      - run:
          name: Installing GCC 
          command: 'unlink /usr/bin/g++ && ln -s /usr/bin/g++-8 /usr/bin/g++'
      - run:
          name: Creating Build Files
          command: 'bash scripts/compile.sh && bash scripts/test.sh'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
